# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/
wallpaper {
    monitor =
    path = ~/.wallpapers/catppuccin-mocha-black-hole.jxl
    fit_mode = cover
}

# Remove the splash text on the wallpaper.
splash = false
