# Start tmux with fish shell
set -g default-command fish

# Allow mouse use (when resizing a pane, etc.).
set -g mouse on

# Allow images to pass through.
set -gq allow-passthrough on

# Set the terminal tmux is running on to kitty.
set -ag terminal-overrides "xterm-kitty"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Enabled focus events (for Neovim autoread)
set-option -g focus-events on

set-option -sg escape-time 10
